version: "3.3"
services:
  app:
    image: node:12.16.3
    build:
      context: .
    expose:
      - "4200"
    ports:
      - "4200:4200"
    volumes:
      - "./src/:/code"
    command: ng serve --host 0.0.0.0 --open --port 4200