version: '3.1'
services:
  mongo_database:
    image: mongo
    restart: always
    expose:
        - "27017"
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
